### ISSUE TITLE
ArcGIS Pro 2.0

### ISSUE THREAD

**Issue by wspiking** [Esri/ago-clone-items#2]
Hello,

When adding the toolbox to Pro 2.0 using the provided directions I'm not able to find the 'Clone Items tool with the Geoprocessing search pane and when I manually add the toolbox through the Catalog view I'm unable to see or edit any of the parameters.  I'm running ArcGIS API for Python version 1.2.0....not sure if that matters or not.

Any help would be appreciated.

Thank you,

Bill

**Comment by chris-fox** [comment]
Hi Bill,

I wasn't able to reproduce these issues at 2.0. Maybe you could share some screenshots? Specifically of what you are seeing not being able to see or edit any of the parameters?

This is what I see after adding the toolbox to the project:

![image](https://user-images.githubusercontent.com/6796763/29174758-4b3640ae-7db5-11e7-9051-1fe45dce6e5c.png)

This is what I see after opening the tool:

![image](https://user-images.githubusercontent.com/6796763/29174805-656200b2-7db5-11e7-9739-b7c088da69a0.png)

**Comment by wspiking** [comment]
Hi Chris,

Here's what I'm seeing.

![capture](https://user-images.githubusercontent.com/5851986/29178454-3d32ffcc-7db7-11e7-8d3d-187d6e727a01.PNG)

I'm thinking it probably has less to do with your script and more to do with how the script is accessing the python api on my computer.

Thank you for checking.

Bill

**Comment by chris-fox** [comment]
Bill, I haven't seen this before, normally if there was a problem with importing a module you would get a red x next to the toolbox.

In the python window in Pro can you try importing the arcgis module and let me know if you get an error

import arcgis

**Comment by wspiking** [comment]
Thank you again for following up Chris.  I’m not getting an error when importing the arcgis module.

![screenshot1](https://user-images.githubusercontent.com/5851986/29221731-70d9b1b2-7e85-11e7-9ed4-ea5e2b891ed1.png)


[cid:image010.png@01D31286.80B4B340]

Bill Spiking | GIS Analyst/Project Manager
Direct +1 (816) 412-1780 | Main +1 (816) 412-1741 | Cell +1 (816) 520-9269 | [cid:image001.png@01D31286.6C5231C0] <https://www.linkedin.com/in/billspiking>

Tetra Tech | Complex World, Clear Solutions™ | Environmental Services Divisions
415 Oak Street | Kansas City, MO 64106 | tetratech.com

This message, including any attachments, may include privileged, confidential and/or inside information. Any distribution or use of this communication by anyone other than the intended recipient is strictly prohibited and may be unlawful. If you are not the intended recipient, please notify the sender by replying to this message and then delete it from your system.

[cid:image011.png@01D31286.80B4B340]<http://www.facebook.com/tetratech>  [cid:image012.png@01D31286.80B4B340] <http://www.twitter.com/tetratech>   [cid:image013.png@01D31286.80B4B340] <http://www.linkedin.com/company/tetra-tech>    Please consider the environment before printing. Read more<http://www.tetratech.com/sustainability>
[cid:image014.png@01D31286.80B4B340]<http://www.tetratech.com/50th>

**Comment by wspiking** [comment]
When running the example.py in the python window I get the error below.  It’s looking for the clone_items module…..

![screenshot2](https://user-images.githubusercontent.com/5851986/29221748-7d87145e-7e85-11e7-91a0-097ac22c92a1.png)


[cid:image010.png@01D3128B.C0A46630]

Bill Spiking | GIS Analyst/Project Manager
Direct +1 (816) 412-1780 | Main +1 (816) 412-1741 | Cell +1 (816) 520-9269 | [cid:image001.png@01D3128B.A04EA8A0] <https://www.linkedin.com/in/billspiking>

Tetra Tech | Complex World, Clear Solutions™ | Environmental Services Divisions
415 Oak Street | Kansas City, MO 64106 | tetratech.com

This message, including any attachments, may include privileged, confidential and/or inside information. Any distribution or use of this communication by anyone other than the intended recipient is strictly prohibited and may be unlawful. If you are not the intended recipient, please notify the sender by replying to this message and then delete it from your system.

[cid:image011.png@01D3128B.C0A46630]<http://www.facebook.com/tetratech>  [cid:image012.png@01D3128B.C0A46630] <http://www.twitter.com/tetratech>   [cid:image013.png@01D3128B.C0A46630] <http://www.linkedin.com/company/tetra-tech>    Please consider the environment before printing. Read more<http://www.tetratech.com/sustainability>
[cid:image014.png@01D3128B.C0A46630]<http://www.tetratech.com/50th>

**Comment by chris-fox** [comment]
Hi Bill,

When you reply to the e-mail directly rather than going back to github I don't get your screenshots. However, I would expect it would fail to find that module because it by default isn't in the pro python search path. It should work for the tool because the clone_items.py file is in the same directory as the toolbox. You could make it work in the python window by adding the folder containing the clone_items.py to the python search path before you attempt to run the code from the example.py.

sys.path.append('path to folder containing clone_items.py')

**Comment by wspiking** [comment]
Thank you Chris, I added the images back via github.  I’ll give the sys.path.append a try…..still at a loss why I can’t your toolbox to work.

Bill Spiking | GIS Analyst/Project Manager
Direct +1 (816) 412-1780 | Main +1 (816) 412-1741 | Cell +1 (816) 520-9269 | [cid:image001.png@01D3129A.F458A4F0] <https://www.linkedin.com/in/billspiking>

Tetra Tech | Complex World, Clear Solutions™ | Environmental Services Divisions
415 Oak Street | Kansas City, MO 64106 | tetratech.com

This message, including any attachments, may include privileged, confidential and/or inside information. Any distribution or use of this communication by anyone other than the intended recipient is strictly prohibited and may be unlawful. If you are not the intended recipient, please notify the sender by replying to this message and then delete it from your system.

[cid:image006.png@01D3129A.F45D5FE0]<http://www.facebook.com/tetratech>  [cid:image007.png@01D3129A.F45D5FE0] <http://www.twitter.com/tetratech>   [cid:image008.png@01D3129A.F45D5FE0] <http://www.linkedin.com/company/tetra-tech>    Please consider the environment before printing. Read more<http://www.tetratech.com/sustainability>
[cid:image009.png@01D3129A.F45D5FE0]<http://www.tetratech.com/50th>

**Comment by wspiking** [comment]
Hi Chris,

I got the example.py working with the sys.path.append, though when trying to clone a web map it never completes.  The script creates the Output folder and begins cloning the feature layers, but eventually the script stops and then removes the feature layers from my account.  It works fine cloning the feature layers independently, but is getting hung up with the web maps.   My web maps are complex with many hosed feature layers, map image layers, and a vector basemap.

Thank you,

Bill

**Comment by chris-fox** [comment]
I would have to debug it to figure out the issue, it is expected if an error is encountered along the way that it will cleanup any layers that have already been created, The script doesn't support map image layers, so it won't clone those. Is the web map and layers public? If so could you share the item id of the web map?

**Comment by wspiking** [comment]
I'd like to help you debug, but unfortunately I can't make the web map and layers public.  I'll do some more testing to see if I can figure out the issue.  I wonder if the issue is a tile layer.  In the account I'm copying from I've got privileges  to publish tile layers, but in the new account I don't.

**Comment by chris-fox** [comment]
If you run the example.py from a python IDE it should print out messages along the way including the exception that cause the script to fail.
